# SPDX-License-Identifier: GPL-3.0-or-later
function New-PSTSMLogWrapper {
    <#
    .SYNOPSIS
        Generates the small shim script that gives a scheduled task a per-run transcript and a
        meaningful Last Run Result.
    .DESCRIPTION
        Task Scheduler captures nothing. Without this, a task that fails at 3am leaves you with
        a single hex code and no output, and a script that ends without an explicit exit code
        reports 0x0 whether it worked or not.

        The wrapper is deliberately thin:
          - starts a transcript named <TaskName>_<timestamp>.log
          - splats the original arguments through unchanged, so named parameters still bind
          - turns a terminating error into exit 1 instead of a silent success
          - propagates the script's own $LASTEXITCODE when it set one
          - prunes logs older than RetentionDays

        It is written to <ScriptDir>\.pstsm\<TaskName>.wrapper.ps1, regenerated on every
        registration, and carries a do-not-edit header - it is build output, not source.
    .PARAMETER Plan
        The task plan. Uses ScriptPath, TaskName and the Logging block.
    .OUTPUTS
        [string] Full path to the generated wrapper.
    #>
    [CmdletBinding(SupportsShouldProcess)]
    param(
        [Parameter(Mandatory)]
        [object]$Plan
    )

    $scriptDir = Split-Path -Path $Plan.ScriptPath -Parent
    $wrapperDir = Join-Path $scriptDir '.pstsm'
    $safeName = ($Plan.TaskName -replace '[\\/:*?"<>|]', '-')
    $wrapperPath = Join-Path $wrapperDir "$safeName.wrapper.ps1"

    $logDir = $Plan.Logging.Directory
    $retention = [int]$Plan.Logging.RetentionDays

    # Single-quoted here-string: nothing below is expanded now. The three placeholders are
    # substituted afterwards so a script path containing $ or ` cannot break the wrapper.
    $template = @'
<#
    GENERATED BY PSTSM - DO NOT EDIT.
    Regenerated every time the task is saved. Edit the task, not this file.

    Wraps the real script so the scheduled task produces a transcript and a truthful
    Last Run Result.
#>

# Deliberately NO param() block and NO [CmdletBinding()]. An advanced-function parameter
# using ValueFromRemainingArguments swallows the '-Name' tokens and re-binds the values
# positionally, so '-Label "hello world"' reaches the real script as two positional
# arguments and parameter binding fails. The automatic $args variable preserves the tokens
# verbatim, and array splatting re-binds them as the named parameters they were. Verified
# on Windows PowerShell 5.1 and PowerShell 7.
$forwardedArgs = $args

$ErrorActionPreference = 'Continue'

$scriptPath    = '__SCRIPT_PATH__'
$logDirectory  = '__LOG_DIR__'
$retentionDays = __RETENTION__

if (-not (Test-Path -LiteralPath $logDirectory)) {
    New-Item -ItemType Directory -Path $logDirectory -Force | Out-Null
}

$stamp   = Get-Date -Format 'yyyyMMdd-HHmmss'
$logFile = Join-Path $logDirectory ('__TASK_NAME___' + $stamp + '.log')

$exitCode = 0
try {
    Start-Transcript -Path $logFile -Force | Out-Null
}
catch {
    # A transcript that cannot start must not stop the task from running.
    Write-Warning "Could not start transcript: $($_.Exception.Message)"
}

try {
    Write-Output "[$(Get-Date -Format s)] Starting $scriptPath"
    Write-Output "[$(Get-Date -Format s)] Running as $([Security.Principal.WindowsIdentity]::GetCurrent().Name)"
    if ($forwardedArgs.Count -gt 0) { Write-Output "[$(Get-Date -Format s)] Arguments: $($forwardedArgs -join ' ')" }

    $global:LASTEXITCODE = 0

    if ($forwardedArgs.Count -gt 0) { & $scriptPath @forwardedArgs } else { & $scriptPath }

    if ($null -ne $LASTEXITCODE) { $exitCode = $LASTEXITCODE }
    Write-Output "[$(Get-Date -Format s)] Completed with exit code $exitCode"
}
catch {
    # Without this a terminating error still leaves Last Run Result at 0x0.
    $exitCode = 1
    Write-Output "[$(Get-Date -Format s)] FAILED: $($_.Exception.Message)"
    Write-Output $_.ScriptStackTrace
}
finally {
    try { Stop-Transcript | Out-Null } catch { }

    if ($retentionDays -gt 0) {
        try {
            $cutoff = (Get-Date).AddDays(-$retentionDays)
            # Scoped to THIS task's own transcripts. A bare '*.log' swept the whole directory -
            # and the default directory is the script's own Logs folder, so it deleted the
            # script's application logs, other PSTSM tasks' transcripts, and anything else that
            # happened to live there. Silently, inside a finally, behind SilentlyContinue.
            # -Filter's only wildcards are * and ?, both removed by the name sanitiser.
            Get-ChildItem -LiteralPath $logDirectory -Filter '__TASK_NAME___*.log' -ErrorAction SilentlyContinue |
                Where-Object { $_.LastWriteTime -lt $cutoff } |
                Remove-Item -Force -ErrorAction SilentlyContinue
        }
        catch { }
    }
}

exit $exitCode
'@

    # Every placeholder lands inside a single-quoted string in the template, so every one needs
    # its apostrophes doubled. __TASK_NAME__ was the one that did not: a task called
    # "O'Brien Report" produced a wrapper that failed to parse, so the task registered happily and
    # then failed on every single run with a bare parse error and no transcript to explain it.
    # $safeName itself stays undoubled - it is also the wrapper's filename.
    # ONE pass with a map, not a chain of .Replace calls. Chained, each replacement can substitute
    # into the output of the previous one: a task named "Has__RETENTION__Inside" came out as
    # "Has30Inside" and the task then failed on every run. The trigger is absurd, but the previous
    # ordering was only accidentally safe, and a single pass costs nothing.
    $map = @{
        '__SCRIPT_PATH__' = ($Plan.ScriptPath -replace "'", "''")
        '__LOG_DIR__'     = ($logDir -replace "'", "''")
        '__TASK_NAME__'   = ($safeName -replace "'", "''")
        '__RETENTION__'   = $retention.ToString()
    }
    $content = [regex]::Replace($template, '__(?:SCRIPT_PATH|LOG_DIR|TASK_NAME|RETENTION)__', {
            param($m) $map[$m.Value]
        })

    if ($PSCmdlet.ShouldProcess($wrapperPath, 'Write task log wrapper')) {
        if (-not (Test-Path -LiteralPath $wrapperDir)) {
            New-Item -ItemType Directory -Path $wrapperDir -Force | Out-Null
        }

        # UTF-8 WITH BOM. The wrapper is launched by whichever engine the task targets, and
        # Windows PowerShell 5.1 reads a BOM-less file as ANSI.
        $utf8Bom = New-Object System.Text.UTF8Encoding($true)
        [System.IO.File]::WriteAllText($wrapperPath, $content, $utf8Bom)
    }

    $wrapperPath
}
